# Generated by Django 5.0 on 2024-02-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
